# Generated by Django 5.1.7 on 2025-03-27 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lovehub", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apptheme",
            options={},
        ),
        migrations.AlterField(
            model_name="apptheme",
            name="theme",
            field=models.CharField(
                choices=[
                    ("default", "پیش\u200cفرض"),
                    ("dark", "تاریک"),
                    ("light", "روشن"),
                    ("nature", "طبیعت"),
                    ("romance", "رمانتیک"),
                ],
                default="default",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="apptheme",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="theme",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_shared", models.BooleanField(default=False)),
                ("is_important", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
