# Generated by Django 5.1.7 on 2025-03-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lovehub", "0002_alter_apptheme_options_alter_apptheme_theme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailymood",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="یادداشت"),
        ),
    ]
