# Generated by Django 5.1.7 on 2025-03-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lovehub", "0003_dailymood_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishitem",
            name="is_important",
            field=models.BooleanField(default=False, verbose_name="مهم"),
        ),
    ]
