# Generated by Django 5.1.7 on 2025-03-27 23:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lovehub", "0004_wishitem_is_important"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="زمان ایجاد"
            ),
        ),
    ]
