# Generated by Django 5.1.7 on 2025-03-27 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lovehub", "0005_event_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("message", models.TextField(verbose_name="پیام")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("event", "رویداد"),
                            ("moment", "لحظه"),
                            ("wish", "آرزو"),
                            ("comment", "نظر"),
                            ("system", "سیستمی"),
                        ],
                        default="system",
                        max_length=20,
                        verbose_name="نوع اعلان",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="خوانده شده"),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="لینک"
                    ),
                ),
                (
                    "related_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="شناسه شیء مرتبط"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "اعلان",
                "verbose_name_plural": "اعلان\u200cها",
                "ordering": ["-created_at"],
            },
        ),
    ]
