# Generated by Django 5.1.7 on 2025-03-28 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lovehub", "0006_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, verbose_name="اعلان\u200cها فعال است"
                    ),
                ),
                (
                    "notify_events",
                    models.BooleanField(default=True, verbose_name="اعلان رویدادها"),
                ),
                (
                    "notify_moments",
                    models.BooleanField(default=True, verbose_name="اعلان لحظات"),
                ),
                (
                    "notify_wishes",
                    models.BooleanField(default=True, verbose_name="اعلان آرزوها"),
                ),
                (
                    "notify_comments",
                    models.BooleanField(default=True, verbose_name="اعلان نظرات"),
                ),
                (
                    "notification_method",
                    models.CharField(
                        choices=[
                            ("app", "درون برنامه\u200cای"),
                            ("email", "ایمیل"),
                            ("both", "هر دو"),
                        ],
                        default="app",
                        max_length=10,
                        verbose_name="روش اعلان",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات اعلان",
                "verbose_name_plural": "تنظیمات اعلان\u200cها",
            },
        ),
        migrations.CreateModel(
            name="PrivacySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_tracking",
                    models.BooleanField(
                        default=True, verbose_name="ردیابی فعالیت\u200cها"
                    ),
                ),
                (
                    "data_sharing",
                    models.BooleanField(
                        default=True, verbose_name="اشتراک\u200cگذاری داده\u200cها"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات حریم خصوصی",
                "verbose_name_plural": "تنظیمات حریم خصوصی",
            },
        ),
        migrations.CreateModel(
            name="UserWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال است"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_widgets",
                        to="lovehub.dashboardwidget",
                        verbose_name="ویجت",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویجت کاربر",
                "verbose_name_plural": "ویجت\u200cهای کاربر",
                "ordering": ["order"],
                "unique_together": {("user", "widget")},
            },
        ),
    ]
