# Generated by Django 5.1.7 on 2025-03-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lovehub", "0007_notificationsettings_privacysettings_userwidget"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="enable_notification",
            field=models.BooleanField(
                default=False, verbose_name="فعال\u200cسازی یادآوری"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="notification_days",
            field=models.PositiveIntegerField(
                default=1, verbose_name="روزهای قبل از یادآوری"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="notification_method",
            field=models.CharField(
                choices=[
                    ("app", "درون برنامه\u200cای"),
                    ("email", "ایمیل"),
                    ("both", "هر دو"),
                ],
                default="app",
                max_length=10,
                verbose_name="روش اعلان",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="notify_partner",
            field=models.BooleanField(default=True, verbose_name="یادآوری به همسر"),
        ),
    ]
