# Generated by Django 5.1.7 on 2025-03-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lovehub", "0008_event_enable_notification_event_notification_days_and_more"),
    ]

    operations = []
