# Generated by Django 5.1.7 on 2025-03-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lovehub", "0009_auto_20250328_1821"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsettings",
            name="notify_daily_messages",
            field=models.BooleanField(
                default=True, verbose_name="اعلان پیام\u200cهای روزانه"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("event", "رویداد"),
                    ("moment", "لحظه"),
                    ("wish", "آرزو"),
                    ("comment", "نظر"),
                    ("system", "سیستمی"),
                    ("daily_message", "پیام روزانه"),
                ],
                default="system",
                max_length=20,
                verbose_name="نوع اعلان",
            ),
        ),
    ]
