# Generated by Django 5.1.7 on 2025-03-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lovehub", "0010_notificationsettings_notify_daily_messages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apptheme",
            name="color_palette",
            field=models.CharField(
                choices=[
                    ("default", "پیش\u200cفرض"),
                    ("purple", "بنفش"),
                    ("blue", "آبی"),
                    ("green", "سبز"),
                    ("orange", "نارنجی"),
                    ("red", "قرمز"),
                    ("pink", "صورتی"),
                    ("teal", "فیروزه\u200cای"),
                ],
                default="default",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="apptheme",
            name="font_size",
            field=models.CharField(
                choices=[("small", "کوچک"), ("medium", "متوسط"), ("large", "بزرگ")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="apptheme",
            name="theme",
            field=models.CharField(
                choices=[
                    ("default", "پیش\u200cفرض"),
                    ("dark", "تاریک"),
                    ("light", "روشن"),
                    ("nature", "طبیعت"),
                    ("romance", "رمانتیک"),
                    ("royal", "سلطنتی"),
                    ("ocean", "اقیانوس"),
                    ("sunset", "غروب آفتاب"),
                ],
                default="default",
                max_length=20,
            ),
        ),
    ]
